# 在local环境运行
local:  
  port: 8566
  host: 0.0.0.0
  mongo_url: mongodb://localhost:27017
  img_path: /home/imag # 服务器文件存储路路径
  img_url: http://xxxx/statics/ # 文件获取url
# 在线上环境运行
prod:
  port: 8666
  host: 0.0.0.0
  mongo_url: mongodb://